name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.0.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd public_html
          git pull
          yarn install --check-files
          composer install --no-dev
          yarn grunt build